# -------------------  --------------------
# ------------------- ApplicationContextInitializer --------------------
context:
  initializer:
    classes: org.study.config.MyApplicationContextInitializer
